
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
opacity = 0.98
title = "HackAcritty"

[window.padding]
x = 5
y = 5
